#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Moves commonink.app from Common Ink v1 (paudrow/commonink) to v2 (paudrow/common-ink-v2), with v1
# staying up at v1.commonink.app. Run it from anywhere: every gh call names its repository.
#
# The order matters. A custom domain belongs to one Worker at a time, so v1's deploy has to let go of
# commonink.app before v2's deploy can take it.

V1_REPO="paudrow/commonink"
V2_REPO="paudrow/common-ink-v2"
V1_BRANCH="v1-subdomain"
V2_BRANCH="domain-cutover"
# set_secret and set_var write to this repository.
export GH_REPO="$V2_REPO"
# Only values that aren't secret are remembered between runs, outside any repository.
ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/common-ink/cutover.env"
mkdir -p "$(dirname "$ENV_FILE")"

# pr_url REPO BRANCH: the pull request for a branch.
pr_url() { gh pr view "$2" -R "$1" --json url -q .url 2>/dev/null || echo "https://github.com/$1/pulls"; }

# watch_deploy REPO: waits for the newest CI run on main and says whether it passed.
watch_deploy() {
  local id
  sleep 10
  id=$(gh run list -R "$1" --branch main --event push --limit 1 --json databaseId -q '.[0].databaseId')
  if [[ -z "$id" ]]; then warn "no run on main yet; watch it at https://github.com/$1/actions"; pause "Press Enter once its deploy job is green"; return; fi
  note "watching run $id (Ctrl-C stops watching, not the deploy)"
  if gh run watch "$id" -R "$1" --exit-status >/dev/null; then
    printf '  %s✓ deployed%s\n' "$GREEN" "$RESET"
  else
    warn "the run failed: https://github.com/$1/actions/runs/$id"
    pause "Fix it and re-run the deploy, then press Enter"
  fi
}

# returns_to NAME URL ORIGIN: whether a sign-in start sends Google this origin's callback.
returns_to() {
  local location
  location=$(curl -s -o /dev/null -w '%{redirect_url}' --max-time 15 "$2" || true)
  if [[ "$location" == *"redirect_uri=$(printf '%s' "$3" | sed 's#:#%3A#; s#/#%2F#g')"* ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else
    printf '  %s✗ %s%s: Google would return to %s\n' "$RED" "$1" "$RESET" "${location#*redirect_uri=}"
  fi
}

# check NAME URL WANT_STATUS WANT_LOCATION_PREFIX: one request, without following redirects.
check() {
  local name="$1" url="$2" want="$3" where="${4:-}" status location
  status=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$url" || echo "000")
  location=$(curl -s -o /dev/null -w '%{redirect_url}' --max-time 15 "$url" || true)
  if [[ "$status" == "$want" && "$location" == "$where"* ]]; then
    printf '  %s✓%s %s %s(%s %s)%s\n' "$GREEN" "$RESET" "$name" "$DIM" "$status" "${location:0:70}" "$RESET"
  else
    printf '  %s✗ %s%s: got %s %s, wanted %s %s\n' "$RED" "$name" "$RESET" "$status" "${location:0:70}" "$want" "$where"
  fi
}

TOTAL_STAGES=9

banner "Move commonink.app to Common Ink v2"

stage "Before you start"
say "This moves commonink.app and www.commonink.app to Common Ink v2. v1 keeps"
say "running at v1.commonink.app, with Google sign-in. Nothing from v1 is copied."
say ""
say "Order: Google console, then GitHub settings, then merge v1, wait for its"
say "deploy, then merge v2. Between the two deploys commonink.app is down for"
say "a few minutes."
if ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't signed in. Run 'gh auth login' in another terminal first."
  pause "Press Enter once it is"
fi
note "v1 pull request: $(pr_url "$V1_REPO" "$V1_BRANCH")"
note "v2 pull request: $(pr_url "$V2_REPO" "$V2_BRANCH")"
pause

stage "Cloudflare: let v2's deploy token change domains"
say "Deploying a custom domain needs Workers Routes: Edit on the zone. v1's token"
say "has it; v2's may only have Workers Scripts and R2."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Find the token v2's CLOUDFLARE_API_TOKEN secret holds (GitHub can't show it,"
step "so go by its name). If it's the same token v1 uses, there's nothing to do."
step "Otherwise: ... > Edit. Add Zone > Workers Routes > Edit, under Zone Resources"
step "Include > Specific zone > commonink.app. Continue to summary > Update token."
note "Editing a token's permissions keeps its value, so the secret stays right."
pause "Press Enter when the token can edit Workers Routes on commonink.app"

stage "Google Cloud: redirect addresses for v1's new home"
say "v1 and v2 share one OAuth client. Google returns only to addresses it lists."
open_url "https://console.cloud.google.com/auth/clients"
step "Google Auth Platform > Clients. Open the Web client Common Ink uses."
step "Under Authorized redirect URIs, keep https://commonink.app/auth/google/callback"
step "(v2 uses it from now on) and add both of these, for v1:"
say "    https://v1.commonink.app/auth/google/callback"
say "    https://v1.commonink.app/auth/google/calendar/callback"
step "Save. It can take a few minutes to apply."
say ""
step "From the same page, copy the Client ID."
ask GOOGLE_CLIENT_ID "Paste the Client ID (ends in .apps.googleusercontent.com):"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
step "Copy the client secret too. If it's hidden, the client's page has"
step "Add secret; a new one works alongside the old, so v1 keeps working."
ask_secret GOOGLE_CLIENT_SECRET "Paste the client secret (hidden):"
pause

stage "Google Cloud: what v2 asks for"
say "v2 reads and writes calendar events, lists your calendars, and reads contacts."
open_url "https://console.cloud.google.com/auth/scopes"
step "Google Auth Platform > Data access > Add or remove scopes. Make sure these are on the list (v1's"
step "own scopes stay too):"
say "    https://www.googleapis.com/auth/calendar.events"
say "    https://www.googleapis.com/auth/calendar.calendarlist.readonly"
say "    https://www.googleapis.com/auth/contacts.readonly"
step "Update, then Save."
pause "Press Enter for the audience"
open_url "https://console.cloud.google.com/auth/audience"
step "Publishing status: Testing. Leave it there for now."
step "Test users: make sure each person who signs in is listed."
note "In Testing, Google ends access after 7 days. v2 asks you to reconnect then."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
open_url "https://console.cloud.google.com/apis/library/people.googleapis.com"
step "In the two tabs that just opened, both APIs show Enabled (v1 uses them already)."
pause

stage "GitHub: v2's sign-in settings"
say "These go to $V2_REPO, and the next deploy sends them to the Worker."
note "GitHub and Cloudflare never show a secret again, which is why you paste them."
ask ALLOWED_EMAILS "Who may sign in (comma-separated) [audrow@nashmail.co]:"
ALLOWED_EMAILS="${ALLOWED_EMAILS:-audrow@nashmail.co}"
write_env ALLOWED_EMAILS "$ALLOWED_EMAILS"
set_var GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
set_var ALLOWED_EMAILS "$ALLOWED_EMAILS"
[[ -n "$GOOGLE_CLIENT_SECRET" ]] && set_secret GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
if gh secret list -R "$V2_REPO" 2>/dev/null | grep -q '^SESSION_SECRET'; then
  note "SESSION_SECRET is set already. A new one signs everyone out of v2, and Google Calendar asks to be connected again (its refresh token is sealed with it)."
  if confirm "Make a new SESSION_SECRET anyway?"; then set_secret SESSION_SECRET "$(openssl rand -base64 32)"; fi
else
  set_secret SESSION_SECRET "$(openssl rand -base64 32)"
fi
unset GOOGLE_CLIENT_SECRET
pause

stage "Merge v1's pull request"
say "v1 moves to v1.commonink.app and lets go of commonink.app and www."
open_url "$(pr_url "$V1_REPO" "$V1_BRANCH")"
step "Check it's green, then merge it (squash, as v1 does)."
if ! confirm "Merged?"; then warn "Stopping here. Re-run when you're ready."; exit 1; fi
say "Waiting for v1's deploy on main."
watch_deploy "$V1_REPO"
pause

stage "Check v1 let go of commonink.app"
say "v1 should answer at v1.commonink.app, and send sign-in back there."
check "v1 answers" "https://v1.commonink.app/" 200
check "v1 sign-in returns to v1" "https://v1.commonink.app/auth/google" 302 "https://accounts.google.com/"
returns_to "Google returns to v1.commonink.app" "https://v1.commonink.app/auth/google" "https://v1.commonink.app/auth/google/callback"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the commonink Worker (v1), then its Domains tab (or Settings > Domains"
step "& Routes): only v1.commonink.app is listed, not commonink.app or www."
note "A new certificate can take a few minutes; a 5xx right after deploy is normal."
if ! confirm "Is commonink.app gone from v1's domains?"; then warn "v2's deploy would fail to take the domain. Stopping."; exit 1; fi

stage "Merge v2's pull request"
say "v2 takes commonink.app and www.commonink.app."
open_url "$(pr_url "$V2_REPO" "$V2_BRANCH")"
step "Check it's green, then merge it."
if ! confirm "Merged?"; then warn "Stopping here. Re-run when you're ready."; exit 1; fi
say "Waiting for v2's deploy on main."
watch_deploy "$V2_REPO"
pause

stage "Check both sign in"
check "www goes to the apex" "https://www.commonink.app/" 301 "https://commonink.app/"
check "v2 sends you to sign in" "https://commonink.app/" 302 "https://commonink.app/auth/google"
check "v2 sign-in goes to Google" "https://commonink.app/auth/google" 302 "https://accounts.google.com/"
returns_to "Google returns to commonink.app" "https://commonink.app/auth/google" "https://commonink.app/auth/google/callback"
check "v1's shared links go to v1" "https://commonink.app/s/check" 302 "https://v1.commonink.app/s/check"
check "v1 still signs in" "https://v1.commonink.app/auth/google" 302 "https://accounts.google.com/"
say ""
step "Now in the browser: sign in at commonink.app, then ⌘⇧P > Connect Google"
step "calendar and contacts. Then sign in at v1.commonink.app too."
open_url "https://commonink.app/"
pause "Press Enter once both let you in"

finish
